"""
Contract Management Dashboard — DAX Measures Catalog
=====================================================

This file lists every DAX measure grouped by target table. It is consumed by the
MCP server's pbip_add_measures tool (one call per table). Each measure already
encodes its format string, display folder, and description, and the DAX has been
written to the patterns preferred by the server's DAX linter:

  - DIVIDE(n, d) instead of n / d
  - Boolean-filter predicates inside CALCULATE (no FILTER over whole table)
  - Variables for reused sub-expressions
  - SUMMARIZECOLUMNS-friendly base measures
  - Quoted table names where needed (Payments, Deliverables)

Table reference (after Phase 1 Power Query import):
  - Agreements            (1 row per contract; the hub table)
  - Payments    (one row per payment milestone)
  - Deliverables (one row per right / obligation / VIK item)

Notes
-----
- The Date table is generated by pbip_create_date_table and is named "Date".
- The active Date relationship is Date[Date] 1:M Payments[Due_Date].
- A second (inactive) relationship Date[Date] 1:M Agreements[Start_Date] is
  activated with USERELATIONSHIP for contract-value time intelligence.
"""

# --------------------------------------------------------------------------- #
# Measures on the Agreements table — Portfolio & Lifecycle
# --------------------------------------------------------------------------- #
AGREEMENTS_MEASURES = [
    # ---- Base financials ----
    {
        "name": "Total Contract Value",
        "expression": "SUM(Agreements[Total_Contract_Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Base",
        "description": "Sum of Total_Contract_Value_AED across all agreements in scope.",
    },
    {
        "name": "Total Annual Value",
        "expression": "SUM(Agreements[Annual_Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Base",
        "description": "Sum of the annualized contract value (Annual_Value_AED).",
    },
    {
        "name": "Avg Contract Value",
        "expression": "AVERAGE(Agreements[Total_Contract_Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Base",
        "description": "Average Total_Contract_Value_AED per agreement.",
    },
    {
        "name": "Max Contract Value",
        "expression": "MAX(Agreements[Total_Contract_Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Base",
        "description": "Largest single contract value in scope.",
    },
    # ---- Counts ----
    {
        "name": "Total Agreements",
        "expression": "COUNTROWS(Agreements)",
        "format_string": "#,##0",
        "display_folder": "Counts",
        "description": "Count of agreement rows (one per contract).",
    },
    {
        "name": "Active Contracts",
        "expression": "CALCULATE([Total Agreements], Agreements[Status] = \"Active\")",
        "format_string": "#,##0",
        "display_folder": "Counts",
        "description": "Count of agreements whose Status is Active.",
    },
    {
        "name": "Active Contract Value",
        "expression": "CALCULATE([Total Contract Value], Agreements[Status] = \"Active\")",
        "format_string": "#,##0",
        "display_folder": "Counts",
        "description": "Total contract value of Active-status agreements.",
    },
    {
        "name": "Contracts with Renewal Option",
        "expression": "CALCULATE([Total Agreements], Agreements[Renewal_Option] = \"Yes\")",
        "format_string": "#,##0",
        "display_folder": "Counts",
        "description": "Count of agreements that have a renewal option.",
    },
    {
        "name": "Auto Renewal Contracts",
        "expression": "CALCULATE([Total Agreements], Agreements[Auto_Renewal] = \"Yes\")",
        "format_string": "#,##0",
        "display_folder": "Counts",
        "description": "Count of agreements that auto-renew.",
    },
    # ---- Lifecycle / expiry ----
    {
        "name": "Avg Term Months",
        "expression": "AVERAGE(Agreements[Term_Months])",
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Average contract term length in months.",
    },
    {
        "name": "Days to Expiry",
        "expression": "DATEDIFF(TODAY(), MAX(Agreements[End_Date]), DAY)",
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Days from today to the latest agreement End_Date in scope.",
    },
    {
        "name": "Contracts Expiring 90d",
        "expression": (
            "CALCULATE(\n"
            "    [Total Agreements],\n"
            "    Agreements[End_Date] >= TODAY(),\n"
            "    Agreements[End_Date] <= TODAY() + 90\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Agreements whose End_Date falls within the next 90 days.",
    },
    {
        "name": "Contracts Expiring 180d",
        "expression": (
            "CALCULATE(\n"
            "    [Total Agreements],\n"
            "    Agreements[End_Date] >= TODAY(),\n"
            "    Agreements[End_Date] <= TODAY() + 180\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Agreements whose End_Date falls within the next 180 days.",
    },
    {
        "name": "Contracts Expiring 365d",
        "expression": (
            "CALCULATE(\n"
            "    [Total Agreements],\n"
            "    Agreements[End_Date] >= TODAY(),\n"
            "    Agreements[End_Date] <= TODAY() + 365\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Agreements whose End_Date falls within the next 365 days.",
    },
    {
        "name": "Expired Still Active Flag",
        "expression": (
            "CALCULATE(\n"
            "    [Total Agreements],\n"
            "    Agreements[Status] = \"Active\",\n"
            "    Agreements[End_Date] < TODAY()\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Lifecycle",
        "description": "Data-quality flag: Active agreements whose End_Date has passed. Should be 0.",
    },
    # ---- Counterparty concentration ----
    {
        "name": "Unique Counterparties",
        "expression": "DISTINCTCOUNT(Agreements[Counterparty_Name])",
        "format_string": "#,##0",
        "display_folder": "Counterparties",
        "description": "Count of distinct counterparty names.",
    },
    # ---- Time intelligence (uses Date relationship via Start_Date, inactive) ----
    {
        "name": "YTD Contract Value",
        "expression": (
            "CALCULATE(\n"
            "    [Total Contract Value],\n"
            "    USERELATIONSHIP('Date'[Date], Agreements[Start_Date]),\n"
            "    TOTALYTD('Date'[Date])\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Time Intelligence",
        "description": "Year-to-date Total Contract Value by Start_Date.",
    },
    {
        "name": "PY Contract Value",
        "expression": (
            "CALCULATE(\n"
            "    [Total Contract Value],\n"
            "    USERELATIONSHIP('Date'[Date], Agreements[Start_Date]),\n"
            "    SAMEPERIODLASTYEAR('Date'[Date])\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Time Intelligence",
        "description": "Total Contract Value for the same period last year.",
    },
    {
        "name": "YoY Contract Growth",
        "expression": "[Total Contract Value] - [PY Contract Value]",
        "format_string": "#,##0;-#,##0",
        "display_folder": "Time Intelligence",
        "description": "Difference vs the same period last year.",
    },
    {
        "name": "YoY Growth %",
        "expression": (
            "VAR _py = [PY Contract Value]\n"
            "RETURN DIVIDE([Total Contract Value] - _py, _py)"
        ),
        "format_string": "0.0%;-0.0%",
        "display_folder": "Time Intelligence",
        "description": "Year-over-year growth percentage (safe DIVIDE).",
    },
]

# --------------------------------------------------------------------------- #
# Measures on the Payments table — Cashflow & Collections
# --------------------------------------------------------------------------- #
PAYMENT_SCHEDULE_MEASURES = [
    {
        "name": "Total Payment Amount",
        "expression": "SUM(Payments[Amount_AED])",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Sum of scheduled payment amounts (AED).",
    },
    {
        "name": "Paid Amount",
        "expression": "CALCULATE([Total Payment Amount], Payments[Status] = \"Paid\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Total amount of paid milestones.",
    },
    {
        "name": "Invoiced Amount",
        "expression": "CALCULATE([Total Payment Amount], Payments[Status] = \"Invoiced\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Total amount of invoiced (not yet paid) milestones.",
    },
    {
        "name": "Overdue Amount",
        "expression": "CALCULATE([Total Payment Amount], Payments[Status] = \"Overdue\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Total amount of overdue payments.",
    },
    {
        "name": "Due Amount",
        "expression": "CALCULATE([Total Payment Amount], Payments[Status] = \"Due\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Total amount of payments currently Due.",
    },
    {
        "name": "Outstanding Amount",
        "expression": (
            "CALCULATE(\n"
            "    [Total Payment Amount],\n"
            "    Payments[Status] IN {\"Not Due\", \"Due\", \"Invoiced\", \"Overdue\"}\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Total amount still outstanding (Not Due + Due + Invoiced + Overdue).",
    },
    {
        "name": "Payment Collection Rate",
        "expression": "DIVIDE([Paid Amount], [Total Payment Amount])",
        "format_string": "0.0%",
        "display_folder": "Payments",
        "description": "Paid share of total scheduled value.",
    },
    {
        "name": "Upcoming Payments 30d",
        "expression": (
            "CALCULATE(\n"
            "    [Total Payment Amount],\n"
            "    Payments[Due_Date] >= TODAY(),\n"
            "    Payments[Due_Date] <= TODAY() + 30,\n"
            "    Payments[Status] IN {\"Not Due\", \"Due\"}\n"
            ")"
        ),
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Scheduled amount due in the next 30 days and not yet paid/invoiced.",
    },
    {
        "name": "Payment Count",
        "expression": "COUNTROWS(Payments)",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Count of scheduled payment milestones.",
    },
    {
        "name": "Paid Count",
        "expression": "CALCULATE([Payment Count], Payments[Status] = \"Paid\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Count of paid milestones.",
    },
    {
        "name": "Avg Days To Due",
        "expression": "AVERAGE(Payments[Days_To_Due])",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Average Days_To_Due across milestones in scope.",
    },
    {
        "name": "VIK Payment Amount",
        "expression": "CALCULATE([Total Payment Amount], Payments[Payment_Type] = \"Value In Kind\")",
        "format_string": "#,##0",
        "display_folder": "Payments",
        "description": "Scheduled VIK (Value In Kind) amount.",
    },
]

# --------------------------------------------------------------------------- #
# Measures on the Deliverables table — Obligations & Delivery tracking
# --------------------------------------------------------------------------- #
DELIVERABLES_MEASURES = [
    {
        "name": "Total Deliverables",
        "expression": "COUNTROWS(Deliverables)",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of all deliverable/right/obligation rows.",
    },
    {
        "name": "Delivered Count",
        "expression": "CALCULATE([Total Deliverables], Deliverables[Status] = \"Delivered\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of items delivered.",
    },
    {
        "name": "In Progress Count",
        "expression": "CALCULATE([Total Deliverables], Deliverables[Status] = \"In Progress\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of items in progress.",
    },
    {
        "name": "Not Started Count",
        "expression": "CALCULATE([Total Deliverables], Deliverables[Status] = \"Not Started\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of items not started.",
    },
    {
        "name": "Overdue Deliverables Count",
        "expression": "CALCULATE([Total Deliverables], Deliverables[Status] = \"Overdue\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of overdue deliverables.",
    },
    {
        "name": "Applicable Deliverables",
        "expression": "CALCULATE([Total Deliverables], Deliverables[Applicable] = \"Yes\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Count of items where Applicable = Yes.",
    },
    {
        "name": "Completion Rate",
        "expression": "DIVIDE([Delivered Count], [Applicable Deliverables])",
        "format_string": "0.0%",
        "display_folder": "Deliverables",
        "description": "Delivered / Applicable deliverables.",
    },
    {
        "name": "Total VIK Value",
        "expression": "CALCULATE(SUM(Deliverables[Value_AED]), Deliverables[Item_Group] = \"VIK\")",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Total known AED value of VIK items.",
    },
    {
        "name": "Total Deliverable Value",
        "expression": "SUM(Deliverables[Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Sum of Value_AED across all deliverables (blanks excluded).",
    },
    {
        "name": "Avg Deliverable Value",
        "expression": "AVERAGEX(Deliverables, Deliverables[Value_AED])",
        "format_string": "#,##0",
        "display_folder": "Deliverables",
        "description": "Average value of a single deliverable (excludes blanks).",
    },
]

# --------------------------------------------------------------------------- #
# Top-level export map: target_table -> measures list
# Used by apply_measures.py to drive pbip_add_measures calls.
# --------------------------------------------------------------------------- #
MEASURES_BY_TABLE = {
    "Agreements": AGREEMENTS_MEASURES,
    "Payments": PAYMENT_SCHEDULE_MEASURES,
    "Deliverables": DELIVERABLES_MEASURES,
}

if __name__ == "__main__":
    total = 0
    for tbl, ms in MEASURES_BY_TABLE.items():
        print(f"\n{tbl}: {len(ms)} measures")
        for m in ms:
            print(f"  - {m['name']}  ({m['display_folder']})  fmt={m.get('format_string','')}")
            total += 1
    print(f"\nTotal: {total} measures across {len(MEASURES_BY_TABLE)} tables")