table Deliverables
	lineageTag: 5e8e99c6-db1d-4c43-94b9-260fa3b38a0c

	measure 'Total Deliverables' = COUNTROWS(Deliverables)
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 5438f79b-cb0b-46e5-8cbf-fdbd28b43081

	measure 'Delivered Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Delivered")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 508e9b09-c77c-433f-b3cf-58b1af50358e

	measure 'In Progress Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "In Progress")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: c5cbc89a-9635-41a5-8145-44481ae26030

	measure 'Not Started Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Not Started")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: a4506da9-b633-4565-952c-93d99545c6ed

	measure 'Overdue Deliverables Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Overdue")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 6774cf57-b793-428e-9646-d50dbc2962b9

	measure 'Applicable Deliverables' = CALCULATE([Total Deliverables], Deliverables[Applicable] = "Yes")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: d1991e9f-0404-493d-9645-9025c30ffc01

	measure 'Completion Rate' = DIVIDE([Delivered Count], [Applicable Deliverables])
		formatString: 0.0%
		displayFolder: Deliverables
		lineageTag: 4e6eeb2e-a680-4b16-a41d-ac841126f8cd

	measure 'Total VIK Value' = CALCULATE(SUM(Deliverables[Value_AED]), Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 493cf30f-8eaa-48f2-a903-687403c29248

	measure 'Total Deliverable Value' = SUM(Deliverables[Value_AED])
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 6f8a2125-fb37-4693-8346-21fee5971a54

	measure 'Avg Deliverable Value' = AVERAGEX(Deliverables, Deliverables[Value_AED])
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 468a9cf3-3746-4512-823f-6dd28e1a4d58

	measure 'Deliverables Due 30d' = CALCULATE([Total Deliverables], Deliverables[Due_Date] >= TODAY(), Deliverables[Due_Date] <= TODAY() + 30, Deliverables[Status] <> "Delivered")
		formatString: #,##0
		displayFolder: Delivery
		lineageTag: dff03dfb-6cc1-4d17-a631-50e0cdd02404

	measure 'Deliverables Past Due' = CALCULATE([Total Deliverables], Deliverables[Due_Date] < TODAY(), Deliverables[Status] <> "Delivered")
		formatString: #,##0
		displayFolder: Delivery
		lineageTag: 3edf6a45-5f48-475c-8dc8-03ef539a2784

	measure 'Deliverables Without Evidence' = CALCULATE([Delivered Count], Deliverables[Evidence_Link] = BLANK())
		formatString: #,##0
		displayFolder: Compliance
		lineageTag: 10451dd6-deaa-4cc3-8000-b264d29a53d4

	measure 'Avg VIK Value Per Item' = DIVIDE([Total VIK Value], CALCULATE([Total Deliverables], Deliverables[Item_Group] = "VIK"))
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: d4d1d0a6-68f7-4666-82e8-f3644df01a59

	measure 'Items Not Applicable' = CALCULATE([Total Deliverables], Deliverables[Applicable] = "No")
		formatString: #,##0
		displayFolder: Deliverables
		lineageTag: 3eaf0257-a1bd-4fe2-931a-b2fb15ee1a2a

	column Item_ID
		dataType: string
		lineageTag: 84ef47a7-aa6a-4ce3-90b7-bd2dcabb85d8
		summarizeBy: none
		sourceColumn: Item_ID

		annotation SummarizationSetBy = Automatic

	column Agreement_ID
		dataType: string
		lineageTag: b125a211-51ed-462b-970c-d93734097dc1
		summarizeBy: none
		sourceColumn: Agreement_ID

		annotation SummarizationSetBy = Automatic

	column Item_Group
		dataType: string
		lineageTag: 4d663697-01e0-48be-849b-b45204b0ae0c
		summarizeBy: none
		sourceColumn: Item_Group

		annotation SummarizationSetBy = Automatic

	column Item_Category
		dataType: string
		lineageTag: d652b136-3218-4115-bb7b-183195deeb30
		summarizeBy: none
		sourceColumn: Item_Category

		annotation SummarizationSetBy = Automatic

	column Item_Name
		dataType: string
		lineageTag: c39e147b-680d-4d7d-8fe9-f1318cda88ed
		summarizeBy: none
		sourceColumn: Item_Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 2f4283e6-87e0-483c-b3d5-0a599fe07fba
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d0534b0f-7615-4f45-8bf4-feae972a1a59
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: adbe3b41-c0fc-457d-852d-c932f4b3e2b3
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value_AED
		dataType: int64
		formatString: 0
		lineageTag: cf11d04f-4979-41ef-a02d-20c833d9af6a
		summarizeBy: sum
		sourceColumn: Value_AED

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: 156789f7-2590-4377-86e2-f2ca99c99746
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column Due_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0ee98c4-1b3d-4963-a727-f626ecdd13d7
		summarizeBy: none
		sourceColumn: Due_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Season
		dataType: string
		lineageTag: d2aad8d6-0627-442c-b76e-ae988d72769c
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: ceddab38-3d98-4bc9-88d2-9377ebf6cd0d
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Responsible_Party
		dataType: string
		lineageTag: d0e49f16-edb1-433e-82a6-ddb44feef4d1
		summarizeBy: none
		sourceColumn: Responsible_Party

		annotation SummarizationSetBy = Automatic

	column Applicable
		dataType: string
		lineageTag: ddb9594f-f026-48ab-a63f-85b5a982e4d6
		summarizeBy: none
		sourceColumn: Applicable

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0abd9965-78c7-48dc-8e89-5df9ba70511c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Date_Delivered
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f222921-c1fa-4b88-9ccf-7a1a8d4190f1
		summarizeBy: none
		sourceColumn: Date_Delivered

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Evidence_Link
		dataType: string
		lineageTag: 2c4713ba-80a2-407e-aece-6cd907a6bd1a
		summarizeBy: none
		sourceColumn: Evidence_Link

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: c5366a19-937d-48b9-b47f-641d86e42448
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Due
		dataType: string
		lineageTag: 5fb968a3-a0d7-41f0-9e47-02716f550ebb
		summarizeBy: none
		sourceColumn: Due

		annotation SummarizationSetBy = Automatic

	partition Deliverables = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\danie\Code\power-bi-contracts\contracts_data_collection_template.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DeliverablesTable", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Item_ID", type text}, {"Agreement_ID", type text}, {"Item_Group", type text}, {"Item_Category", type text}, {"Item_Name", type text}, {"Description", type text}, {"Quantity", Int64.Type}, {"Unit", type text}, {"Value_AED", Int64.Type}, {"Frequency", type text}, {"Season", type text}, {"Owner", type text}, {"Responsible_Party", type text}, {"Applicable", type text}, {"Status", type text}, {"Date_Delivered", type date}}, "en-US"),
				  #"Replaced Value" = Table.ReplaceValue(#"Changed column type", "600 Delivered", "Delivered", Replacer.ReplaceText, {"Status"}),
				  #"Changed Due_Date Type" = Table.TransformColumns(#"Replaced Value", {{"Due_Date", each try Date.From(_) otherwise null, type nullable date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Due_Date Type", each [Item_ID] <> null and [Item_ID] <> "")
				in
				  #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	/// Total AED value of VIK deliverables.
	measure 'VIK Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of VIK deliverables.
	measure 'VIK Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered VIK items.
	measure 'VIK Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue VIK deliverables.
	measure 'VIK Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Reporting

	/// VIK delivery completion rate.
	measure 'VIK Completion %' =
			VAR _cnt = [VIK Count]
			RETURN DIVIDE([VIK Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of Commercial Rights deliverables.
	measure 'Commercial Rights Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "Commercial Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of Commercial Rights deliverables.
	measure 'Commercial Rights Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "Commercial Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered Commercial Rights items.
	measure 'Commercial Rights Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "Commercial Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue Commercial Rights deliverables.
	measure 'Commercial Rights Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "Commercial Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Commercial Rights delivery completion rate.
	measure 'Commercial Rights Completion %' =
			VAR _cnt = [Commercial Rights Count]
			RETURN DIVIDE([Commercial Rights Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of Advertisement Rights deliverables.
	measure 'Advertisement Rights Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "Advertisement Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of Advertisement Rights deliverables.
	measure 'Advertisement Rights Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "Advertisement Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered Advertisement Rights items.
	measure 'Advertisement Rights Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "Advertisement Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue Advertisement Rights deliverables.
	measure 'Advertisement Rights Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "Advertisement Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Advertisement Rights delivery completion rate.
	measure 'Advertisement Rights Completion %' =
			VAR _cnt = [Advertisement Rights Count]
			RETURN DIVIDE([Advertisement Rights Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of Ticketing & Hospitality deliverables.
	measure 'Ticketing Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "Ticketing & Hospitality")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of Ticketing & Hospitality deliverables.
	measure 'Ticketing Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "Ticketing & Hospitality")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered Ticketing & Hospitality items.
	measure 'Ticketing Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "Ticketing & Hospitality")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue Ticketing & Hospitality deliverables.
	measure 'Ticketing Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "Ticketing & Hospitality")
		formatString: #,##0
		displayFolder: Reporting

	/// Ticketing & Hospitality delivery completion rate.
	measure 'Ticketing Completion %' =
			VAR _cnt = [Ticketing Count]
			RETURN DIVIDE([Ticketing Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of PRO League Obligation deliverables.
	measure 'UAE PL Obligations Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "PRO League Obligation")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of PRO League Obligation deliverables.
	measure 'UAE PL Obligations Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "PRO League Obligation")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered PRO League Obligation items.
	measure 'UAE PL Obligations Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "PRO League Obligation")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue PRO League Obligation deliverables.
	measure 'UAE PL Obligations Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "PRO League Obligation")
		formatString: #,##0
		displayFolder: Reporting

	/// PRO League Obligation delivery completion rate.
	measure 'UAE PL Obligations Completion %' =
			VAR _cnt = [UAE PL Obligations Count]
			RETURN DIVIDE([UAE PL Obligations Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of Supplier Service deliverables.
	measure 'Supplier Service Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "Supplier Service")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of Supplier Service deliverables.
	measure 'Supplier Service Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "Supplier Service")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered Supplier Service items.
	measure 'Supplier Service Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "Supplier Service")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue Supplier Service deliverables.
	measure 'Supplier Service Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "Supplier Service")
		formatString: #,##0
		displayFolder: Reporting

	/// Supplier Service delivery completion rate.
	measure 'Supplier Service Completion %' =
			VAR _cnt = [Supplier Service Count]
			RETURN DIVIDE([Supplier Service Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting

	/// Total AED value of Additional Rights deliverables.
	measure 'Additional Rights Value' = CALCULATE([Total Deliverable Value], Deliverables[Item_Group] = "Additional Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of Additional Rights deliverables.
	measure 'Additional Rights Count' = CALCULATE([Total Deliverables], Deliverables[Item_Group] = "Additional Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of delivered Additional Rights items.
	measure 'Additional Rights Delivered' = CALCULATE([Delivered Count], Deliverables[Item_Group] = "Additional Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Count of overdue Additional Rights deliverables.
	measure 'Additional Rights Overdue' = CALCULATE([Overdue Deliverables Count], Deliverables[Item_Group] = "Additional Rights")
		formatString: #,##0
		displayFolder: Reporting

	/// Additional Rights delivery completion rate.
	measure 'Additional Rights Completion %' =
			VAR _cnt = [Additional Rights Count]
			RETURN DIVIDE([Additional Rights Delivered], _cnt)
		formatString: 0.0%
		displayFolder: Reporting
