table Deliverables
	lineageTag: 5e8e99c6-db1d-4c43-94b9-260fa3b38a0c

	column Item_ID
		dataType: string
		lineageTag: 84ef47a7-aa6a-4ce3-90b7-bd2dcabb85d8
		summarizeBy: none
		sourceColumn: Item_ID

		annotation SummarizationSetBy = Automatic

	column Agreement_ID
		dataType: string
		lineageTag: b125a211-51ed-462b-970c-d93734097dc1
		summarizeBy: none
		sourceColumn: Agreement_ID

		annotation SummarizationSetBy = Automatic

	column Item_Group
		dataType: string
		lineageTag: 4d663697-01e0-48be-849b-b45204b0ae0c
		summarizeBy: none
		sourceColumn: Item_Group

		annotation SummarizationSetBy = Automatic

	column Item_Category
		dataType: string
		lineageTag: d652b136-3218-4115-bb7b-183195deeb30
		summarizeBy: none
		sourceColumn: Item_Category

		annotation SummarizationSetBy = Automatic

	column Item_Name
		dataType: string
		lineageTag: c39e147b-680d-4d7d-8fe9-f1318cda88ed
		summarizeBy: none
		sourceColumn: Item_Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 2f4283e6-87e0-483c-b3d5-0a599fe07fba
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d0534b0f-7615-4f45-8bf4-feae972a1a59
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: adbe3b41-c0fc-457d-852d-c932f4b3e2b3
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value_AED
		dataType: int64
		formatString: 0
		lineageTag: cf11d04f-4979-41ef-a02d-20c833d9af6a
		summarizeBy: sum
		sourceColumn: Value_AED

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: 156789f7-2590-4377-86e2-f2ca99c99746
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column Due_Date
		dataType: string
		lineageTag: e0ee98c4-1b3d-4963-a727-f626ecdd13d7
		summarizeBy: none
		sourceColumn: Due_Date

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: d2aad8d6-0627-442c-b76e-ae988d72769c
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: ceddab38-3d98-4bc9-88d2-9377ebf6cd0d
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Responsible_Party
		dataType: string
		lineageTag: d0e49f16-edb1-433e-82a6-ddb44feef4d1
		summarizeBy: none
		sourceColumn: Responsible_Party

		annotation SummarizationSetBy = Automatic

	column Applicable
		dataType: string
		lineageTag: ddb9594f-f026-48ab-a63f-85b5a982e4d6
		summarizeBy: none
		sourceColumn: Applicable

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0abd9965-78c7-48dc-8e89-5df9ba70511c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Date_Delivered
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f222921-c1fa-4b88-9ccf-7a1a8d4190f1
		summarizeBy: none
		sourceColumn: Date_Delivered

		variation Variation
			isDefault
			relationship: 25def133-44d8-4c6d-8385-342bbc710e39
			defaultHierarchy: LocalDateTable_cf75335d-de26-4b87-859d-3b8048138fd4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Evidence_Link
		dataType: string
		lineageTag: 2c4713ba-80a2-407e-aece-6cd907a6bd1a
		summarizeBy: none
		sourceColumn: Evidence_Link

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: c5366a19-937d-48b9-b47f-641d86e42448
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	partition Deliverables = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\danie\Code\power-bi-contracts\contracts_data_collection_template.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DeliverablesTable", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Item_ID", type text}, {"Agreement_ID", type text}, {"Item_Group", type text}, {"Item_Category", type text}, {"Item_Name", type text}, {"Description", type text}, {"Quantity", Int64.Type}, {"Unit", type text}, {"Value_AED", Int64.Type}, {"Frequency", type text}, {"Season", type text}, {"Owner", type text}, {"Responsible_Party", type text}, {"Applicable", type text}, {"Status", type text}, {"Date_Delivered", type date}}, "en-US"),
				    #"Filtered Rows" = Table.SelectRows(#"Changed column type", each [Item_ID] <> null and [Item_ID] <> "")
				in
				  #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	measure 'Total Deliverables' = COUNTROWS(Deliverables)
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Delivered Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Delivered")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'In Progress Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "In Progress")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Not Started Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Not Started")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Overdue Deliverables Count' = CALCULATE([Total Deliverables], Deliverables[Status] = "Overdue")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Applicable Deliverables' = CALCULATE([Total Deliverables], Deliverables[Applicable] = "Yes")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Completion Rate' = DIVIDE([Delivered Count], [Applicable Deliverables])
		formatString: 0.0%
		displayFolder: Deliverables

	measure 'Total VIK Value' = CALCULATE(SUM(Deliverables[Value_AED]), Deliverables[Item_Group] = "VIK")
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Total Deliverable Value' = SUM(Deliverables[Value_AED])
		formatString: #,##0
		displayFolder: Deliverables

	measure 'Avg Deliverable Value' = AVERAGEX(Deliverables, Deliverables[Value_AED])
		formatString: #,##0
		displayFolder: Deliverables
